import 'package:flutter/material.dart';
import '../app/theme.dart';
import '../models/topic.dart';

/// Mock data source standing in for the real DDS-backed discovery service.
///
/// Topic list and stats are ported directly from the HandyROS.dc.html
/// design mockup so the UI matches it exactly. Once the native DDS layer
/// (`handyros_core`) is wired up via FFI, this is the seam to replace.
class FakeTopicService {
  static List<Topic> getTopics() {
    return [
      Topic.withNodes(
        id: 1,
        name: '/camera/image_raw',
        type: 'sensor_msgs/msg/Image',
        category: 'image',
        icon: Icons.photo_camera,
        color: AppColors.pri,
        hz: 30,
        hzAvg: '29.8 Hz',
        bandwidth: '44 MB/s',
        messageSize: '1.5 MB',
        latency: '12 ms',
        qos: const QosProfile(
          reliability: 'best_effort',
          history: 'keep_last',
          durability: 'volatile',
          depth: 5,
        ),
        publishers: const [NodeRef('/v4l2_camera', 'tb4@192.168.1.21')],
        subscribers: const [
          NodeRef('/image_proc', 'tb4@192.168.1.21'),
          NodeRef('/web_bridge', 'laptop@.1.10'),
        ],
      ),
      Topic.withNodes(
        id: 2,
        name: '/camera/image_raw/compressed',
        type: 'sensor_msgs/msg/CompressedImage',
        category: 'image',
        icon: Icons.image,
        color: AppColors.pri,
        hz: 30,
        hzAvg: '30.0 Hz',
        bandwidth: '6 MB/s',
        messageSize: '210 KB',
        latency: '9 ms',
        qos: const QosProfile(
          reliability: 'best_effort',
          history: 'keep_last',
          durability: 'volatile',
          depth: 10,
        ),
        publishers: const [NodeRef('/image_transport', 'tb4@192.168.1.21')],
        subscribers: const [NodeRef('/web_bridge', 'laptop@.1.10')],
      ),
      Topic.withNodes(
        id: 3,
        name: '/imu',
        type: 'sensor_msgs/msg/Imu',
        category: 'imu',
        icon: Icons.threed_rotation,
        color: AppColors.sec,
        hz: 100,
        hzAvg: '99.9 Hz',
        bandwidth: '52 KB/s',
        messageSize: '320 B',
        latency: '2 ms',
        qos: const QosProfile(
          reliability: 'reliable',
          history: 'keep_last',
          durability: 'volatile',
          depth: 100,
        ),
        publishers: const [NodeRef('/imu_driver', 'tb4@192.168.1.21')],
        subscribers: const [
          NodeRef('/ekf_localization', 'tb4@192.168.1.21'),
          NodeRef('/imu_logger', 'laptop@.1.10'),
          NodeRef('/madgwick_filter', 'tb4@192.168.1.21'),
        ],
      ),
      Topic.withNodes(
        id: 4,
        name: '/scan',
        type: 'sensor_msgs/msg/LaserScan',
        category: 'laser',
        icon: Icons.radar,
        color: AppColors.lime,
        hz: 10,
        hzAvg: '9.98 Hz',
        bandwidth: '85 KB/s',
        messageSize: '8.6 KB',
        latency: '5 ms',
        qos: const QosProfile(
          reliability: 'best_effort',
          history: 'keep_last',
          durability: 'volatile',
          depth: 5,
        ),
        publishers: const [NodeRef('/rplidar_node', 'tb4@192.168.1.21')],
        subscribers: const [
          NodeRef('/slam_toolbox', 'tb4@192.168.1.21'),
          NodeRef('/nav2_costmap', 'tb4@192.168.1.21'),
        ],
      ),
      Topic.withNodes(
        id: 5,
        name: '/points',
        type: 'sensor_msgs/msg/PointCloud2',
        category: 'cloud',
        icon: Icons.scatter_plot,
        color: AppColors.pink,
        hz: 15,
        hzAvg: '14.9 Hz',
        bandwidth: '28 MB/s',
        messageSize: '1.9 MB',
        latency: '18 ms',
        qos: const QosProfile(
          reliability: 'best_effort',
          history: 'keep_last',
          durability: 'volatile',
          depth: 5,
        ),
        publishers: const [NodeRef('/depth_camera', 'tb4@192.168.1.21')],
        subscribers: const [NodeRef('/octomap_server', 'tb4@192.168.1.21')],
      ),
      Topic.withNodes(
        id: 6,
        name: '/odom',
        type: 'nav_msgs/msg/Odometry',
        category: 'nav',
        icon: Icons.my_location,
        color: AppColors.amber,
        hz: 50,
        hzAvg: '50.0 Hz',
        bandwidth: '36 KB/s',
        messageSize: '720 B',
        latency: '3 ms',
        qos: const QosProfile(
          reliability: 'reliable',
          history: 'keep_last',
          durability: 'volatile',
          depth: 10,
        ),
        publishers: const [NodeRef('/ekf_localization', 'tb4@192.168.1.21')],
        subscribers: const [
          NodeRef('/nav2_controller', 'tb4@192.168.1.21'),
          NodeRef('/rviz2', 'laptop@.1.10'),
        ],
      ),
      Topic.withNodes(
        id: 7,
        name: '/tf',
        type: 'tf2_msgs/msg/TFMessage',
        category: 'tf',
        icon: Icons.account_tree,
        color: AppColors.blue,
        hz: 100,
        hzAvg: '98.4 Hz',
        bandwidth: '120 KB/s',
        messageSize: '1.2 KB',
        latency: '2 ms',
        qos: const QosProfile(
          reliability: 'reliable',
          history: 'keep_last',
          durability: 'volatile',
          depth: 100,
        ),
        publishers: const [
          NodeRef('/robot_state_publisher', 'tb4@192.168.1.21'),
          NodeRef('/ekf_localization', 'tb4@192.168.1.21'),
        ],
        subscribers: const [
          NodeRef('/nav2_planner', 'tb4@192.168.1.21'),
          NodeRef('/rviz2', 'laptop@.1.10'),
        ],
      ),
      Topic.withNodes(
        id: 8,
        name: '/map',
        type: 'nav_msgs/msg/OccupancyGrid',
        category: 'nav',
        icon: Icons.map,
        color: AppColors.blue,
        hz: 1,
        hzAvg: '1.0 Hz',
        bandwidth: '2.1 MB/s',
        messageSize: '2.1 MB',
        latency: '40 ms',
        qos: const QosProfile(
          reliability: 'reliable',
          history: 'keep_last',
          durability: 'transient_local',
          depth: 1,
        ),
        publishers: const [NodeRef('/slam_toolbox', 'tb4@192.168.1.21')],
        subscribers: const [NodeRef('/nav2_costmap', 'tb4@192.168.1.21')],
      ),
      Topic.withNodes(
        id: 9,
        name: '/cmd_vel',
        type: 'geometry_msgs/msg/Twist',
        category: 'nav',
        icon: Icons.sports_esports,
        color: AppColors.amber,
        hz: 20,
        hzAvg: '20.0 Hz',
        bandwidth: '4 KB/s',
        messageSize: '48 B',
        latency: '1 ms',
        qos: const QosProfile(
          reliability: 'reliable',
          history: 'keep_last',
          durability: 'volatile',
          depth: 10,
        ),
        publishers: const [NodeRef('/nav2_controller', 'tb4@192.168.1.21')],
        subscribers: const [NodeRef('/base_driver', 'tb4@192.168.1.21')],
      ),
      Topic.withNodes(
        id: 10,
        name: '/rosout',
        type: 'rcl_interfaces/msg/Log',
        category: 'diag',
        icon: Icons.terminal,
        color: AppColors.ok,
        hz: 8,
        hzAvg: '7.6 Hz',
        bandwidth: '12 KB/s',
        messageSize: '260 B',
        latency: '4 ms',
        qos: const QosProfile(
          reliability: 'reliable',
          history: 'keep_all',
          durability: 'volatile',
          depth: 1000,
        ),
        publishers: const [NodeRef('/nav2_bt_navigator', 'tb4@192.168.1.21')],
        subscribers: const [NodeRef('/rosout_logger', 'laptop@.1.10')],
      ),
      Topic.withNodes(
        id: 11,
        name: '/battery_state',
        type: 'sensor_msgs/msg/BatteryState',
        category: 'diag',
        icon: Icons.battery_charging_full,
        color: AppColors.pri,
        hz: 1,
        hzAvg: '1.0 Hz',
        bandwidth: '0.4 KB/s',
        messageSize: '96 B',
        latency: '6 ms',
        qos: const QosProfile(
          reliability: 'reliable',
          history: 'keep_last',
          durability: 'volatile',
          depth: 5,
        ),
        publishers: const [NodeRef('/base_driver', 'tb4@192.168.1.21')],
        subscribers: const [NodeRef('/diagnostics_agg', 'tb4@192.168.1.21')],
      ),
      Topic.withNodes(
        id: 12,
        name: '/planner/status',
        type: 'planner_msgs/msg/PlannerStatus',
        category: 'custom',
        icon: Icons.help_outline,
        color: AppColors.custom,
        hz: 5,
        hzAvg: '5.0 Hz',
        bandwidth: '2 KB/s',
        messageSize: '180 B',
        latency: '7 ms',
        qos: const QosProfile(
          reliability: 'reliable',
          history: 'keep_last',
          durability: 'volatile',
          depth: 10,
        ),
        publishers: const [NodeRef('/global_planner', 'tb4@192.168.1.21')],
        subscribers: const [],
      ),
    ];
  }
}
